version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www/html/application
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: W13V1hdgf2
      MYSQL_DATABASE: test_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
